### ISSUE TITLE
Animals spawning issue on version 1.20.2

### ISSUE THREAD

**Issue by Stabrinai** [PaperMC/Folia#161]
### Expected behavior

![Snipaste_2023-10-20_12-19-51](https://github.com/PaperMC/Folia/assets/61693182/40c87b1d-97fe-4ed2-851e-50572aa27025)
![Snipaste_2023-10-20_12-27-04](https://github.com/PaperMC/Folia/assets/61693182/99c0fe06-915d-4672-8768-e53b13e67617)
![Snipaste_2023-10-20_12-26-57](https://github.com/PaperMC/Folia/assets/61693182/cf87c045-3c47-4f3a-8c8d-3435367111ad)

### Observed/Actual behavior

![C24C33EF675D3B8A17BCE3363FB86135](https://github.com/PaperMC/Folia/assets/61693182/d67e590c-44b4-4410-8f6a-53428ba7ecea)
![F1901CE884AC82848660E3D0EB83F03A](https://github.com/PaperMC/Folia/assets/61693182/4714c51a-7cd7-4a76-b661-12b982fd9dbe)
![Snipaste_2023-10-20_12-30-28](https://github.com/PaperMC/Folia/assets/61693182/c6fb1572-21e4-4ca3-99f7-583c2d7c2d2f)
![Snipaste_2023-10-20_12-30-19](https://github.com/PaperMC/Folia/assets/61693182/da0900f6-2cac-495f-b292-f36b586a2233)

### Steps/models to reproduce

use folia ver 1.20.2
join server
wait

### Plugin and Datapack List

![Snipaste_2023-10-20_12-14-57](https://github.com/PaperMC/Folia/assets/61693182/e2d0af40-2eb1-4a5f-8270-5e5d7ed3c995)

### Folia version

This server is running Folia version git-Folia-"757cb09" (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 757cb09 on dev/1.20.2)
Error obtaining version information

### Other

bukkit.yml
```
settings:
  allow-end: true
  warn-on-overload: true
  permissions-file: permissions.yml
  update-folder: update
  plugin-profiling: false
  connection-throttle: 4000
  query-plugins: true
  deprecated-verbose: default
  shutdown-message: Server closed
  minimum-api: none
  use-map-color-cache: true
spawn-limits:
  monsters: 35
  animals: 5
  water-animals: 5
  water-ambient: 10
  water-underground-creature: 5
  axolotls: 5
  ambient: 5
chunk-gc:
  period-in-ticks: 600
ticks-per:
  animal-spawns: 400
  monster-spawns: 1
  water-spawns: 400
  water-ambient-spawns: 400
  water-underground-creature-spawns: 400
  axolotl-spawns: 400
  ambient-spawns: 400
  autosave: 6000
aliases: now-in-commands.yml

```

**Comment by andreypfau** [comment]
Same issue

**Comment by MineSunshineone** [comment]
same

**Comment by DxrkCat** [comment]
same

**Comment by EterNityCH** [comment]
@DxrkCat @MineSunshineone @andreypfau Please refrain from spamming the issue page if you do not have any additional materials to add.

**Comment by andreypfau** [comment]
Any updates?

**Comment by Stabrinai** [comment]
This patch can limit the spawning of animals. You can try it.
```
From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001
From: Sattera <wujiaxin752@icloud.com>
Date: Sat, 11 Nov 2023 14:57:57 +0800
Subject: [PATCH] Try fixing animals spawning issue


diff --git a/src/main/java/net/minecraft/world/level/NaturalSpawner.java b/src/main/java/net/minecraft/world/level/NaturalSpawner.java
index 5caca2a34849189ea42d2699f6d8672e0d7251cb..131dc763c2daee0919f23dc59e0c195e86da29d5 100644
--- a/src/main/java/net/minecraft/world/level/NaturalSpawner.java
+++ b/src/main/java/net/minecraft/world/level/NaturalSpawner.java
@@ -472,6 +472,10 @@ public final class NaturalSpawner {
         MobSpawnSettings biomesettingsmobs = ((Biome) biomeEntry.value()).getMobSettings();
         WeightedRandomList<MobSpawnSettings.SpawnerData> weightedrandomlist = biomesettingsmobs.getMobs(MobCategory.CREATURE);
 
+        if (true){
+            return;
+        }
+
         if (!weightedrandomlist.isEmpty()) {
             int i = chunkPos.getMinBlockX();
             int j = chunkPos.getMinBlockZ();

```

**Comment by Goro922** [comment]
> This patch can limit the spawning of animals. You can try it:
> 
> ```
> From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001
> From: Sattera <wujiaxin752@icloud.com>
> Date: Sat, 11 Nov 2023 22:20:46 +0800
> Subject: [PATCH] Try fixing animals spawning issue
> 
> 
> diff --git a/src/main/java/net/minecraft/world/level/levelgen/NoiseBasedChunkGenerator.java b/src/main/java/net/minecraft/world/level/levelgen/NoiseBasedChunkGenerator.java
> index 58609a0911c4e32b6f80f050cd3d23f70ad75b1b..d47488cc34eda43dd37ebf32802dabe92f1a1984 100644
> --- a/src/main/java/net/minecraft/world/level/levelgen/NoiseBasedChunkGenerator.java
> +++ b/src/main/java/net/minecraft/world/level/levelgen/NoiseBasedChunkGenerator.java
> @@ -406,11 +406,11 @@ public final class NoiseBasedChunkGenerator extends ChunkGenerator {
>      public void spawnOriginalMobs(WorldGenRegion region) {
>          if (!((NoiseGeneratorSettings) this.settings.value()).disableMobGeneration()) {
>              ChunkPos chunkcoordintpair = region.getCenter();
> -            Holder<Biome> holder = region.getBiome(chunkcoordintpair.getWorldPosition().atY(region.getMaxBuildHeight() - 1));
> +            // Holder<Biome> holder = region.getBiome(chunkcoordintpair.getWorldPosition().atY(region.getMaxBuildHeight() - 1));
>              WorldgenRandom seededrandom = new WorldgenRandom(new LegacyRandomSource(RandomSupport.generateUniqueSeed()));
>  
>              seededrandom.setDecorationSeed(region.getSeed(), chunkcoordintpair.getMinBlockX(), chunkcoordintpair.getMinBlockZ());
> -            NaturalSpawner.spawnMobsForChunkGeneration(region, holder, chunkcoordintpair, seededrandom);
> +            // NaturalSpawner.spawnMobsForChunkGeneration(region, holder, chunkcoordintpair, seededrandom);
>          }
>      }
>  }
> ```
> 
> before: ![9061CA7846BFF92795918C205B798C61](https://user-images.githubusercontent.com/61693182/282231158-2772c5ed-8a9f-4e66-acd6-cf3c94e2514e.png) after: ![B88DB4FE322BD58B8772B8FF9528B195](https://user-images.githubusercontent.com/61693182/282231163-bb4ebe38-de5a-4d36-bced-4f44e89c2ea4.png)

nope, still have the same issue
![2023-11-14_21 49 09](https://github.com/PaperMC/Folia/assets/41193535/2f925a03-2465-49aa-bcd4-82a45a595569)

**Comment by Spottedleaf** [comment]
Can't produce this locally at all. 

Please make sure that when you run `git pull` to build newer versions of folia that you also run `gradlew applypatches`, as this looks exactly like a bug that was fixed during the 1.20.2 update

**Comment by cgw2023** [comment]
i can confirm that this problem is still not resolved after the [7aacf90](https://github.com/PaperMC/Folia/commit/7aacf902b0fc917b2874a67f4ebc77077936355d) . I compiled the latest folia jar by cloning the dev/1.20.2 branch after [7aacf90](https://github.com/PaperMC/Folia/commit/7aacf902b0fc917b2874a67f4ebc77077936355d) , still , mobs alot 
![image](https://github.com/PaperMC/Folia/assets/136877036/e72a46fc-0b7d-4c2e-a250-db64f9d923f1)
![image](https://github.com/PaperMC/Folia/assets/136877036/7fc5916e-6a4d-4255-8f53-68b3518b83b5)

**Comment by Goro922** [comment]
![image](https://github.com/PaperMC/Folia/assets/41193535/733662b5-0650-4311-8bc6-3f16adbb1559)

**Comment by Spottedleaf** [comment]
Can you provide your entire config set? spigot, bukkit, and the paper global and paper world configs?

**Comment by cgw2023** [comment]
spigot.yml
https://paste.denizenscript.com/View/117831
bukkit.yml
https://paste.denizenscript.com/View/117833
paper-world-defaults.yml
https://paste.denizenscript.com/View/117834
paper-global.yml
https://paste.denizenscript.com/View/117835

For extra reference plugins are (non of them affect animal spawning and same plugin jars are using in 1.20.1 folia with https://github.com/PaperMC/Folia/commit/372d479cc173cd9d0f91265ebb4b198354717e47):
[01:48:14 INFO]: Server Plugins (40):
[01:48:14 INFO]: Bukkit Plugins:
[01:48:14 INFO]:  - AnnouncerPlus, AntiPopup, Attollo, BetterRTP, BlockLocker, BlueMap, Chunky, ChunkyBorder, CMILib, CodFrame
[01:48:14 INFO]:  CoreProtect, DeluxeMenus, DiscordSRV, DragonDropElytra, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, FancyNpcs
[01:48:14 INFO]:  floodgate, FoliaFlow, GreenChunk, GSit, HeadDrop, Kaiivoid, LuckPerms, Matrix, PlaceholderAPI, PlayerWarps
[01:48:14 INFO]:  ProtocolLib, Residence, ShulkerRespawner, spark, TAB-Bridge, Vault, ViaBackwards, ViaVersion, VillagerOptimizer, zAuctionHouseV3

**Comment by Spottedleaf** [comment]
I can't produce locally still. Can you provide your server.properties as well?

**Comment by Siroshun09** [comment]
Hello!

Our server has been running on Folia since 1.20.1, and when we updated it to 1.20.2, we had an issue similar to this problem. I would like to share my investigation about that issue.

Checking the changes from 1.20.1 to 1.20.2, I noticed that "Per Player Mob Spawning" feature is back.
Our server was originally running on Paper and that feature was still enabled in `paper-world-defaults.yml`.

Looking at the mob spawning process (in `ServerChunkCache#tickChunks`), it resets the mob counts for all players in the world. After limiting this to the local players in the region (`RegionizedWorldData#getLocalPlayers`), this problem seems to have been resolved on our server. If this is the cause, this problem may not be reproducible without multiple regions in the world.

I don't know if this is the correct fix and if there are no side effects, but here is the change:

```patch
             profiler.startTimer(ca.spottedleaf.leafprofiler.LProfilerRegistry.MOB_SPAWN_ENTITY_COUNT); try { // Folia - profiler
             if ((this.spawnFriendlies || this.spawnEnemies) && this.level.paperConfig().entities.spawning.perPlayerMobSpawns) { // don't count mobs when animals and monsters are disabled
                 // re-set mob counts
-                for (ServerPlayer player : this.level.players) {
+                for (ServerPlayer player : regionizedWorldData.getLocalPlayers()) {
                     // Paper start - per player mob spawning backoff
                     for (int ii = 0; ii < ServerPlayer.MOBCATEGORY_TOTAL_ENUMS; ii++) {
                         player.mobCounts[ii] = 0;
```

I hope this helps :)

**Comment by Spottedleaf** [comment]
> Hello!
> 
> Our server has been running on Folia since 1.20.1, and when we updated it to 1.20.2, we had an issue similar to this problem. I would like to share my investigation about that issue.
> 
> Checking the changes from 1.20.1 to 1.20.2, I noticed that "Per Player Mob Spawning" feature is back. Our server was originally running on Paper and that feature was still enabled in `paper-world-defaults.yml`.
> 
> Looking at the mob spawning process (in `ServerChunkCache#tickChunks`), it resets the mob counts for all players in the world. After limiting this to the local players in the region (`RegionizedWorldData#getLocalPlayers`), this problem seems to have been resolved on our server. If this is the cause, this problem may not be reproducible without multiple regions in the world.
> 
> I don't know if this is the correct fix and if there are no side effects, but here is the change:
> 
> ```diff
>              profiler.startTimer(ca.spottedleaf.leafprofiler.LProfilerRegistry.MOB_SPAWN_ENTITY_COUNT); try { // Folia - profiler
>              if ((this.spawnFriendlies || this.spawnEnemies) && this.level.paperConfig().entities.spawning.perPlayerMobSpawns) { // don't count mobs when animals and monsters are disabled
>                  // re-set mob counts
> -                for (ServerPlayer player : this.level.players) {
> +                for (ServerPlayer player : regionizedWorldData.getLocalPlayers()) {
>                      // Paper start - per player mob spawning backoff
>                      for (int ii = 0; ii < ServerPlayer.MOBCATEGORY_TOTAL_ENUMS; ii++) {
>                          player.mobCounts[ii] = 0;
> ```
> 
> I hope this helps :)

This explains it for sure. That's why it doesn't happen locally.

That fix looks correct, if you can PR it I will accept it.

**Comment by Siroshun09** [comment]
Thanks for quick reply.
Okay, I'll prepare PR :)

**Comment by Siroshun09** [comment]
I opened PR #169.

**Comment by Spottedleaf** [comment]
> spigot.yml https://paste.denizenscript.com/View/117831 bukkit.yml https://paste.denizenscript.com/View/117833 paper-world-defaults.yml https://paste.denizenscript.com/View/117834 paper-global.yml https://paste.denizenscript.com/View/117835
> 
> For extra reference plugins are (non of them affect animal spawning and same plugin jars are using in 1.20.1 folia with [372d479](https://github.com/PaperMC/Folia/commit/372d479cc173cd9d0f91265ebb4b198354717e47), extra mob spawn only occur when updated to dev/1.20.2 branch): [01:48:14 INFO]: Server Plugins (40): [01:48:14 INFO]: Bukkit Plugins: [01:48:14 INFO]: - AnnouncerPlus, AntiPopup, Attollo, BetterRTP, BlockLocker, BlueMap, Chunky, ChunkyBorder, CMILib, CodFrame [01:48:14 INFO]: CoreProtect, DeluxeMenus, DiscordSRV, DragonDropElytra, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, FancyNpcs [01:48:14 INFO]: floodgate, FoliaFlow, GreenChunk, GSit, HeadDrop, Kaiivoid, LuckPerms, Matrix, PlaceholderAPI, PlayerWarps [01:48:14 INFO]: ProtocolLib, Residence, ShulkerRespawner, spark, TAB-Bridge, Vault, ViaBackwards, ViaVersion, VillagerOptimizer, zAuctionHouseV3
> 
> Thank you for helping.

Please re-test on https://github.com/PaperMC/Folia/commit/d58fab2cceeabe47b2f0925bb0bde551c46029e9

**Comment by cgw2023** [comment]
> > spigot.yml https://paste.denizenscript.com/View/117831 bukkit.yml https://paste.denizenscript.com/View/117833 paper-world-defaults.yml https://paste.denizenscript.com/View/117834 paper-global.yml https://paste.denizenscript.com/View/117835
> > For extra reference plugins are (non of them affect animal spawning and same plugin jars are using in 1.20.1 folia with [372d479](https://github.com/PaperMC/Folia/commit/372d479cc173cd9d0f91265ebb4b198354717e47), extra mob spawn only occur when updated to dev/1.20.2 branch): [01:48:14 INFO]: Server Plugins (40): [01:48:14 INFO]: Bukkit Plugins: [01:48:14 INFO]: - AnnouncerPlus, AntiPopup, Attollo, BetterRTP, BlockLocker, BlueMap, Chunky, ChunkyBorder, CMILib, CodFrame [01:48:14 INFO]: CoreProtect, DeluxeMenus, DiscordSRV, DragonDropElytra, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, FancyNpcs [01:48:14 INFO]: floodgate, FoliaFlow, GreenChunk, GSit, HeadDrop, Kaiivoid, LuckPerms, Matrix, PlaceholderAPI, PlayerWarps [01:48:14 INFO]: ProtocolLib, Residence, ShulkerRespawner, spark, TAB-Bridge, Vault, ViaBackwards, ViaVersion, VillagerOptimizer, zAuctionHouseV3
> > Thank you for helping.
> 
> Please re-test on [d58fab2](https://github.com/PaperMC/Folia/commit/d58fab2cceeabe47b2f0925bb0bde551c46029e9)

Thank you so much, I already compiled the jar and run it on my production server, if things gets better, my players will tell me and i will update here again.

**Comment by roggy666** [comment]
![image](https://github.com/PaperMC/Folia/assets/59109355/a90510ab-e0e8-4dc2-a169-ec929969cb88)
Same issue on https://github.com/PaperMC/Folia/commit/d58fab2cceeabe47b2f0925bb0bde551c46029e9

This server is running Folia version git-Folia-"3843340" (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 3843340 on dev/1.20.2)

**Comment by roggy666** [comment]
Any news about this problem?

**Comment by Spottedleaf** [comment]
I'm not very certain that screenshot is indicative of anything... does /paper mobcaps or /paper entity list indicate the counts are too high?

**Comment by roggy666** [comment]
![image](https://github.com/PaperMC/Folia/assets/59109355/dfc7ceb0-9e07-45d1-bd1b-475b79dde3b1)
![image](https://github.com/PaperMC/Folia/assets/59109355/ede5c7cb-5293-4708-83f1-2220a81ec306)
My players have night time now, I can repeat this action with more online.

**Comment by Siroshun09** [comment]
Were these creatures spawned after updating to https://github.com/PaperMC/Folia/commit/3843340cba3aac68f5ab54bd8a0cafd2670a9458? (In other words, the creatures that spawned before the fix are not there?)

I created a new server/world and checked out the mob spawn. (with multiple players/regions in the world)
In https://github.com/PaperMC/Folia/commit/7aacf902b0fc917b2874a67f4ebc77077936355d, a large number of creatures spawned such as squids and bats in a short time.
On the other hand, I could not confirm these abnormal spawns in https://github.com/PaperMC/Folia/commit/3843340cba3aac68f5ab54bd8a0cafd2670a9458.

If it can be reproduced by trying it in a new world or by trying to delete a large number of spawned creatures, more investigation may be needed.

**Comment by roggy666** [comment]
Oh, yes much better, but I have another problem. when player hit Zombiefied Piglin they start spawning from all sides as if unlimited

![image](https://github.com/PaperMC/Folia/assets/59109355/53d5d0a7-ffa2-4827-883e-f0c061ed8df1)

**Comment by cgw2023** [comment]
I can also confirm mobs spawning is becoming normal now. I don't see that many mobs in chunks that I have cleared the mobs
However, there is no plugin in folia that can directly show and tp admins to chunks that have alot of mobs, the /tps command in folia in only give a region tp, in most of the cases it cannot tp the admin to the mob's location. 

After the fix, no more new region have mobs more than 2000, but i still have 2 old folia region with mob number 8000+ and i still unable to find where are the mobs . (one in overworld, one in nether, have been flying over more of the region's chunk)

**Comment by roggy666** [comment]
> I can also confirm mobs spawning is becoming normal now. I don't see that many mobs in chunks that I have cleared the mobs However, there is no plugin in folia that can directly show and tp admins to chunks that have alot of mobs, the /tps command in folia in only give a region tp, in most of the cases it cannot tp the admin to the mob's location.
> 
> After the fix, no more new region have mobs more than 2000, but i still have 2 old folia region with mob number 8000+ and i still unable to find where are the mobs . (one in overworld, one in nether, have been flying over more of the region's chunk)

try /minecraft:kill @e[type=mob_type]

**Comment by Yomamaeatstoes** [comment]
There is a plugin called MobStack that supports Folia

**Comment by ocelotpotpie** [comment]
Closing this issue as the spawning problem appears to be solved in https://github.com/PaperMC/Folia/commit/3843340cba3aac68f5ab54bd8a0cafd2670a9458

For any other issues, please open a new ticket. Thanks!

**Comment by cgw2023** [comment]
> > I can also confirm mobs spawning is becoming normal now. I don't see that many mobs in chunks that I have cleared the mobs However, there is no plugin in folia that can directly show and tp admins to chunks that have alot of mobs, the /tps command in folia in only give a region tp, in most of the cases it cannot tp the admin to the mob's location.
> > After the fix, no more new region have mobs more than 2000, but i still have 2 old folia region with mob number 8000+ and i still unable to find where are the mobs . (one in overworld, one in nether, have been flying over more of the region's chunk)
> 
> try /minecraft:kill @e[type=mob_type]

My problem is finding the mobs' location instead of killing the mobs. I have EssentialX which also can do the same thing. But, thx.

**Comment by cgw2023** [comment]
> There is a plugin called MobStack that supports Folia

I can't find it on modrinth, paper hanger or google. Do you have link? thx

**Comment by Goro922** [comment]
> > There is a plugin called MobStack that supports Folia
> 
> I can't find it on modrinth, paper hanger or google. Do you have link? thx

I tried the plugin and I dont recommend using that plugin because there is console spam issue, and I think in general many dev say its useless to use stacking mob plugin.
but if you want to try it anyway you can check it here https://github.com/Nathat23/StackMob-5/tree/folia

**Comment by Yomamaeatstoes** [comment]
There is a upstreamed version that supports Folia 1.20.2 https://github.com/Folia-Inquisitors/StackMob-5-Folia
