### ISSUE TITLE
1.20 crash

### ISSUE THREAD

**Issue by MineSunshineone** [PaperMC/Folia#89]
### Expected behavior

no crash

### Observed/Actual behavior

https://pastes.dev/6oyl2sXTDO

### Steps/models to reproduce

This problem occurs when I open a 1.19.4 archive and use TP

### Plugin and Datapack List

> plugins
[16:55:48 INFO]: Server Plugins (20):
[16:55:48 INFO]: Bukkit Plugins:
[16:55:48 INFO]:  - AnCDK, ArmorStandEditor, Chunky, ColoredAnvils, CoreProtect, CreeperConfetti, DeathMessage, Essentials, EssentialsChat, FreedomChat
[16:55:48 INFO]:  GSit, InvSeePlusPlus, Kaiivoid, LuckPerms, NoFlightInEnd, PistonMOTD, SkullPlugin, TAB, Vault, voicechat

### Folia version

> ver
[16:56:06 INFO]: Checking version, please wait...
[16:56:07 INFO]: This server is running Folia version git-Folia-"3fde784" (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: 3fde784 on dev/1.20)
Error obtaining version information
Previous version: git-Paper-4 (MC: 1.20)

**Comment by jpenilla** [comment]
```diff
diff --git a/patches/server/0014-Block-reading-in-world-tile-entities-on-worldgen-thr.patch b/patches/server/0014-Block-reading-in-world-tile-entities-on-worldgen-thr.patch
index 2ba6b8f..8096f4a 100644
--- a/patches/server/0014-Block-reading-in-world-tile-entities-on-worldgen-thr.patch
+++ b/patches/server/0014-Block-reading-in-world-tile-entities-on-worldgen-thr.patch
@@ -7,7 +7,7 @@ The returned TE may be in the world, in which case it is unsafe
 for the current thread to modify or access its contents.
 
 diff --git a/src/main/java/net/minecraft/world/level/chunk/ImposterProtoChunk.java b/src/main/java/net/minecraft/world/level/chunk/ImposterProtoChunk.java
-index 4a3ac7dedf5cb1e76f16ec4f18e82afc717d0ced..44609fb7965a03283e2bb50e483a8f60254de510 100644
+index 4a3ac7dedf5cb1e76f16ec4f18e82afc717d0ced..603f4fe0817be3d8a443f8b5213bc71a79f0e0ec 100644
 --- a/src/main/java/net/minecraft/world/level/chunk/ImposterProtoChunk.java
 +++ b/src/main/java/net/minecraft/world/level/chunk/ImposterProtoChunk.java
 @@ -84,6 +84,11 @@ public class ImposterProtoChunk extends ProtoChunk {
@@ -22,3 +22,12 @@ index 4a3ac7dedf5cb1e76f16ec4f18e82afc717d0ced..44609fb7965a03283e2bb50e483a8f60
          return this.wrapped.getBlockEntity(pos);
      }
  
+@@ -329,7 +334,7 @@ public class ImposterProtoChunk extends ProtoChunk {
+ 
+     @Override
+     public void initializeLightSources() {
+-        this.wrapped.initializeLightSources();
++        this.wrapped.skyLightSources.fillFrom(this); // Folia - block reading possibly in-world block data for worldgen threads
+     }
+ 
+     @Override
```

This should fix the issue, but it seems like maybe ChunkSkyLightSources usage didn't get removed properly when Starlight was ported? Removing that would also solve the issue.

**Comment by Spottedleaf** [comment]
Fixed by https://github.com/PaperMC/Folia/commit/9b2ffd03cfba3dddd8cd066816ef56cefa0dad22

**Comment by MineSunshineone** [comment]
still occur
[09:29:05 ERROR]: Thread Region Scheduler Thread #2 failed main thread check: Cannot remove entity off-main
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at net.minecraft.world.entity.Entity.setRemoved(Entity.java:5466) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at io.papermc.paper.world.ChunkEntitySlices.unload(ChunkEntitySlices.java:122) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.unloadStage2(NewChunkHolder.java:850) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processUnloads(ChunkHolderManager.java:1306) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at net.minecraft.server.level.ChunkMap.processUnloads(ChunkMap.java:521) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:509) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:455) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:793) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1678) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1535) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:29:05 ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #12 centered at chunk [1416, 1612] in world 'world' failed to tick:
net.minecraft.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1697) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1535) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Cannot remove entity off-main
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at net.minecraft.world.entity.Entity.setRemoved(Entity.java:5466) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at io.papermc.paper.world.ChunkEntitySlices.unload(ChunkEntitySlices.java:122) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.unloadStage2(NewChunkHolder.java:850) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processUnloads(ChunkHolderManager.java:1306) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        at net.minecraft.server.level.ChunkTracker.processUnloads(ChunkTracker.java:521) ~[?:?]
        at net.minecraft.server.level.ChunkTracker.tick(ChunkTracker.java:509) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:455) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:793) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1678) ~[folia-1.20.jar:git-Folia-"9dcd6c2"]
        ... 6 more
[09:29:05 INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[09:29:05 INFO]: [RegionShutdownThread] Scheduler halted
[09:29:05 INFO]: Stopping server

**Comment by electronicboy** [comment]
That error is different to the one reported here.

**Comment by MineSunshineone** [comment]
i will create new issue thanks
